### ISSUE TITLE
feat: Video Stream HTMLVideoElement

### ISSUE THREAD

**Issue by onra2** [robingenz/capacitor-mlkit-plugin-demo#26] opened 2024-08-02 14:50 UTC
**Is your feature request related to a problem? Please describe.**
Not really, but hiding the body in some frameworks feels like a hack, it would be easier if we could get a video stream of the active camera so we can put it in any video html tag. It makes it easier to customize the UI too.

**Describe the solution you'd like**
I would like to be able to show a continuous video preview in a video html tag for a ticket scanning app. The way i want to scan is when the user presses on the screen it activates the scanning capabilities instead of pressing a button and only then showing the camera.

**Describe alternatives you've considered**
The normal way of hiding technically works but it's hard to customize the UI.
What i did try was getting the stream this way:
`
//html ref to the video tag
const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
if (video.value) {
    video.value.srcObject = stream;
}
`

I would be very happy with that feature :) Thanks

**Comment by robingenz** [comment] 2024-08-03 06:45
I close this as duplicate of https://github.com/capawesome-team/capacitor-mlkit/issues/79.

**Closed as not planned by robingenz** 2024-08-03 06:45 UTC
Labels: duplicate, feature
