### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by roboter** [robingenz/capacitor-mlkit-plugin-demo#6] opened 2023-06-25 11:35 UTC
**Describe the bug**
Scanner not working

**To Reproduce**
Build, upload, press scan

**Expected behavior**
Scanner view should appear

**Additional context**
ERROR Error: Uncaught (in promise): Error: Failed to scan code.
Error: Failed to scan code.

Same code as in repo
Tried with Ionic 6 and 7
with version "^5.0.2"

**Comment by robingenz** [comment] 2023-06-25 11:58
I close this is as duplicate of https://github.com/capawesome-team/capacitor-mlkit/issues/38

**Closed as not planned** 2023-06-25 11:58 UTC
Labels: duplicate, bug/fix
